In [11]:
import click
import sys
sys.path.append('C:/Users/inesm/projectos/tennis-predictor/src/data/')
from make_dataset import load_data
from make_dataset import filter_data
from make_dataset import save_data


input_filepath = 'C:/Users/inesm/projectos/tennis-predictor/data/raw/'
output_filepath = 'C:/Users/inesm/projectos/tennis-predictor/data/interim/'

In [9]:
dataset = load_data(input_filepath)
dataset

,ATP,Location,Tournament,Date,Series,Court,Surface,Round,Best of,Winner,...,UBW,UBL,LBW,LBL,SJW,SJL,MaxW,MaxL,AvgW,AvgL
0,1,Adelaide,AAPT Championships,31/12/2001,International,Outdoor,Hard,1st Round,3,Arazi H.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Adelaide,AAPT Championships,31/12/2001,International,Outdoor,Hard,1st Round,3,Carlsen K.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Adelaide,AAPT Championships,31/12/2001,International,Outdoor,Hard,1st Round,3,Chela J.I.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Adelaide,AAPT Championships,31/12/2001,International,Outdoor,Hard,1st Round,3,Draper S.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Adelaide,AAPT Championships,31/12/2001,International,Outdoor,Hard,1st Round,3,Enqvist T.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36358,18,Sao Paulo,Brasil Open,02/03/2018,ATP250,Indoor,Clay,Quarterfinals,3,Zeballos H.,...,NaN,NaN,1.80,2.00,NaN,NaN,1.92,2.05,1.83,1.98
36359,18,Sao Paulo,Brasil Open,02/03/2018,ATP250,Indoor,Clay,Quarterfinals,3,Jarry N.,...,NaN,NaN,2.37,1.57,NaN,NaN,2.44,1.71,2.29,1.63
36360,18,Sao Paulo,Brasil Open,03/03/2018,ATP250,Indoor,Clay,Semifinals,3,Fognini F.,...,NaN,NaN,1.73,2.10,NaN,NaN,1.77,2.27,1.70,2.16
36361,18,Sao Paulo,Brasil Open,03/03/2018,ATP250,Indoor,Clay,Semifinals,3,Jarry N.,...,NaN,NaN,1.80,2.00,NaN,NaN,1.91,2.09,1.85,1.97
36362,18,Sao Paulo,Brasil Open,04/03/2018,ATP250,Indoor,Clay,The Final,3,Fognini F.,...,NaN,NaN,1.36,3.25,NaN,NaN,1.43,3.50,1.36,3.16

In [10]:
dataset = filter_data(dataset)
dataset

,Winner,Loser,WRank,LRank,B365W,B365L,Surface,match_id
1371,Johansson T.,Pretzsch A.,7,133,1.100,6.500,Grass,1371
1413,Morrison J.,Ilie A.,98,176,1.571,2.250,Grass,1413
1409,Lee H.T.,Larsson M.,117,142,2.625,1.444,Grass,1409
1407,Godwin N.,Gasquet R.,111,281,1.533,2.375,Grass,1407
1384,Youzhny M.,Santoro F.,67,32,1.800,1.909,Grass,1384
...,...,...,...,...,...,...,...,...
36335,Bautista Agut R.,Pouille L.,23,15,1.660,2.200,Hard,36335
36302,Anderson K.,Donaldson J.,8,59,1.300,3.500,Hard,36302
36361,Jarry N.,Zeballos H.,73,69,1.900,1.900,Clay,36361
36304,Del Potro J.M.,Anderson K.,9,8,1.500,2.620,Hard,36304
36362,Fognini F.,Jarry N.,20,73,1.360,3.250,Clay,36362

In [ ]:
save_data(dataset, 'dataset.pkl', output_filepath)